# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  server1_ip = "192.168.251.2"
  server2_ip = "192.168.251.3"
  config.vm.define "server1" do |s1|
    s1.vm.box = "opensuse/openSUSE-42.3-x86_64"
    s1.vm.network "forwarded_port", guest: 5432, host: 5432
    s1.vm.network "private_network", ip: server1_ip
    s1.vm.hostname = "reto-fdw-server1.example.local"
    s1.vm.provision "file", source: "db1.sql", destination: "/tmp/db.sql"
    s1.vm.provision "shell", path: "setup1.sh", args: [server1_ip]
  end
  config.vm.define "server2" do |s2|
    s2.vm.box = "opensuse/openSUSE-42.3-x86_64"
    s2.vm.network "forwarded_port", guest: 3306, host: 3306
    s2.vm.network "private_network", ip: server2_ip
    s2.vm.hostname = "reto-fdw-server2.example.local"
    s2.vm.provision "file", source: "db2.sql", destination: "/tmp/db.sql"
    s2.vm.provision "shell", path: "setup2.sh", args: [server2_ip]
  end
end
