# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "juliogonzalez/openSUSE-42.3-x86_64"
  config.vm.network "forwarded_port", guest: 5432, host: 5432
  config.vm.hostname = "extensiones-postgis.example.local"
  config.vm.provision "shell", inline: 'zypper -q in -y postgresql96 postgresql96-server postgresql96-contrib'
  config.vm.provision "shell", inline: 'systemctl enable postgresql'
  config.vm.provision "shell", inline: 'service postgresql start'
  config.vm.provision "shell", inline: 'sudo -u postgres psql -c "CREATE DATABASE postgis"'
end
