# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "opensuse/openSUSE-42.3-x86_64"
  config.vm.hostname = "instalainstalacion-codigo-fuente.example.local"
end
