CREATE DATABASE db1;
CREATE ROLE usuario1 WITH LOGIN PASSWORD 'miclave1';
\c db1
CREATE SCHEMA esquema1;
GRANT ALL ON SCHEMA esquema1 TO usuario1;
GRANT SELECT ON ALL TABLES IN SCHEMA esquema1 TO usuario1;
ALTER DEFAULT PRIVILEGES IN SCHEMA esquema1 GRANT ALL ON TABLES TO usuario1;
